name: xiuxian_app
description: 离线文字修仙与动态因果长河
publish_to: none
version: 1.2.1+6
environment:
  sdk: '>=3.11.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  drift: ^2.34.4
  sqlite3: ^3.5.2
  path_provider: ^2.1.6
  path: ^1.9.1
  dio: ^5.11.1
  flutter_secure_storage: ^11.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/MaShanZheng-OFL.txt
    - assets/fonts/LXGWWenKai-OFL.txt
  fonts:
    - family: MaShan
      fonts:
        - asset: assets/fonts/MaShanZheng-Regular.ttf
    - family: WenKai
      fonts:
        - asset: assets/fonts/LXGWWenKai-Regular.ttf
