part of 'engine.dart';

abstract final class AiProposalValidator {
  static void validate(
    World w,
    String kind,
    Map<String, dynamic> p, {
    String? target,
  }) {
    void reject() => throw const RuleViolation('AI内容校验失败');
    bool text(dynamic value, int max) =>
        value is String &&
        value.trim().isNotEmpty &&
        value.runes.length <= max &&
        !RegExp(r'life-\d+:|:npc:|:relation:|:event:').hasMatch(value);
    if (kind == 'explore') {
      if (p.keys.toSet().difference({'title', 'text', 'options'}).isNotEmpty ||
          !text(p['title'], 40) ||
          !text(p['text'], 600) ||
          p['options'] is! List) {
        reject();
      }
      final options = p['options'] as List;
      final allowed = AdventureRules.catalog(w).map((o) => o.id).toSet();
      final ids = <String>{};
      if (options.length < 2 || options.length > 3) reject();
      for (final o in options) {
        if (o is! Map ||
            o.keys.toSet().difference({'label', 'effect'}).isNotEmpty ||
            !text(o['label'], 40) ||
            o['effect'] is! String ||
            !allowed.contains(o['effect']) ||
            !ids.add(o['effect'])) {
          reject();
        }
      }
      if (!ids.contains('leave')) reject();
    } else if (kind == 'talk') {
      if (p.keys.toSet().difference({'reply', 'news'}).isNotEmpty ||
          !text(p['reply'], 600) ||
          p['news'] is! List) {
        reject();
      }
      final allowed = AdventureRules.intelligence(
        w,
        target ?? '',
      ).map((e) => e['id']).toSet();
      final news = p['news'] as List;
      if (news.length > 2 ||
          news.toSet().length != news.length ||
          news.any((id) => id is! String || !allowed.contains(id))) {
        reject();
      }
    } else if (kind == 'world') {
      if (p.keys.toSet().difference({'action', 'text'}).isNotEmpty ||
          !text(p['text'], 400) ||
          !AdventureRules.worldCatalog(w).any((o) => o['id'] == p['action'])) {
        reject();
      }
    } else {
      reject();
    }
  }
}

/// Proposals reference capabilities generated by rules, never arbitrary effects.
abstract final class AdventureRules {
  static List<EncounterOption> catalog(World w) {
    final local = w.entities.values
        .where(
          (n) =>
              n.type == KarmaNodeType.npc &&
              n.alive &&
              n.location == w.player.location &&
              w.knows(w.playerId, n.id),
        )
        .toList();
    final hurt = local
        .where((n) => n.hp < GameCommandService.maxHp(n))
        .firstOrNull;
    final enemy = local
        .where(
          (n) =>
              n.realm <= w.player.realm + 1 &&
              (n.personality == '好战' ||
                  w.relations.values.any(
                    (r) =>
                        r.source == n.id &&
                        r.target == w.playerId &&
                        r.type == KarmaRelationType.hatred &&
                        !r.resolved,
                  )),
        )
        .firstOrNull;
    return [
      const EncounterOption('herbs', '采集灵草', ['herbs']),
      const EncounterOption('treasure', '拾取遗宝', ['coins']),
      if (hurt != null)
        EncounterOption(
          'rescue',
          '以丹药救助${hurt.name}',
          ['rescue'],
          target: hurt.id,
          pill: true,
        ),
      if ((w.quests['古碑'] ?? 0) < 3)
        const EncounterOption('tablet', '拓下残碑线索', ['quest'], cost: 10),
      if (enemy != null)
        EncounterOption('escort', '护送商旅 · 迎战${enemy.name}', [
          'battle',
          'equipment',
        ], target: enemy.id),
      const EncounterOption('weapon', '修复遗落兵器', ['equipment'], cost: 10),
      if (enemy != null)
        EncounterOption('ambush', '迎战${enemy.name}的伏击', [
          'battle',
          'coins',
        ], target: enemy.id),
      const EncounterOption('spring', '饮用灵泉', ['heal']),
      const EncounterOption('meditate', '借灵泉修炼', ['spirit']),
      const EncounterOption('leave', '离开此缘', []),
    ];
  }

  static Encounter discover(
    World w,
    FactWriter f,
    Map<String, dynamic>? proposal,
  ) {
    final entries = catalog(w);
    const names = {
      'herbs': '灵草秘地',
      'treasure': '古道遗宝',
      'rescue': '负伤修士',
      'tablet': '残碑遗刻',
      'escort': '商旅求援',
      'weapon': '遗落兵器',
      'ambush': '山谷伏击',
      'spring': '灵泉试炼',
    };
    var options = <EncounterOption>[];
    late String title, text;
    if (proposal != null) {
      title = proposal['title'];
      text = proposal['text'];
      options = (proposal['options'] as List).map((o) {
        final base = entries.singleWhere((e) => e.id == o['effect']);
        return EncounterOption(
          base.id,
          o['label'],
          base.effects,
          target: base.target,
          cost: base.cost,
          pill: base.pill,
        );
      }).toList();
    } else {
      final primary = entries.where((o) => names.containsKey(o.id)).toList();
      final chosen = primary[w.adventureRandom.next(primary.length)];
      title = names[chosen.id]!;
      text =
          '${w.entities[w.player.location]!.name}的山路上，你发现${title == '负伤修士' ? '一位真实遇险的修士' : title}。去留之间，因缘将随选择展开。';
      options = [
        chosen,
        if (chosen.id == 'spring')
          entries.singleWhere((e) => e.id == 'meditate'),
        entries.last,
      ];
    }
    if (!options.any((o) => o.leaves)) throw const RuleViolation('奇遇必须允许安全离开');
    final targets = options.map((o) => o.target).whereType<String>().toSet();
    final e = f.event('encounter', title, text, [w.playerId, ...targets]);
    return Encounter(
      w.nextId('encounter'),
      title,
      text,
      options,
      e.id,
      source: proposal == null ? 'local' : 'ai',
    );
  }

  static void choose(World w, FactWriter f, String? id) {
    final encounter = w.encounter;
    if (encounter == null) throw const RuleViolation('没有待处理奇遇');
    final option = encounter.options.where((o) => o.id == id).firstOrNull;
    if (option == null) throw const RuleViolation('无效奇遇选项');
    final fresh = catalog(w).where((o) => o.id == option.id).firstOrNull;
    if (fresh == null || fresh.target != option.target) {
      throw const RuleViolation('人物状态已变化，请离开此缘');
    }
    if (w.player.coins < option.cost) throw const RuleViolation('灵石不足');
    if (option.pill && (w.inventory['回春丹'] ?? 0) < 1) {
      throw const RuleViolation('回春丹不足');
    }
    w.player.coins -= option.cost;
    if (option.pill) w.inventory['回春丹'] = w.inventory['回春丹']! - 1;
    final e = f.event(
      'encounterChoice',
      option.label,
      '选择：${option.label}。${option.requirements}',
      [w.playerId, if (option.target != null) option.target!],
      causes: [Cause(encounter.origin, CausalKind.direct)],
    );
    for (final effect in option.effects) {
      switch (effect) {
        case 'herbs':
          w.inventory['灵草'] = (w.inventory['灵草'] ?? 0) + 3;
        case 'coins':
          if (!option.effects.contains('battle')) {
            w.player.coins += 15 + w.player.realm * 5;
          }
        case 'heal':
          w.player.hp = (w.player.hp + 30).clamp(
            0,
            GameCommandService.maxHp(w.player),
          );
        case 'spirit':
          w.player.spirit += 20 + w.player.realm * 5;
        case 'quest':
          w.quests.putIfAbsent('古碑', () => 0);
        case 'rescue':
          final n = w.entities[option.target]!;
          n.hp = GameCommandService.maxHp(n);
          final rescue = f.event(
            'rescue',
            '救助${n.name}',
            '施以回春丹，保全性命。',
            [w.playerId, n.id],
            causes: [Cause(e.id, CausalKind.direct)],
            importance: 3,
          );
          f.relation(
            n.id,
            w.playerId,
            KarmaRelationType.gratitude,
            rescue,
            strength: 45,
          );
        case 'equipment':
          if (!option.effects.contains('battle')) award(w, f, e.id);
        case 'battle':
          w.battleTarget = option.target;
          final battle = f.event(
            'challenge',
            '迎战${w.entities[option.target]!.name}',
            '选择承担危险，胜利可获得${option.effects.contains('equipment') ? '装备' : '灵石'}。',
            [w.playerId, option.target!],
            causes: [Cause(e.id, CausalKind.direct)],
          );
          w.battleOrigin = battle.id;
          w.battleReward = option.effects.contains('equipment')
              ? 'equipment'
              : 'coins';
          start(w);
      }
    }
    w.encounter = null;
  }

  static Equipment addEquipment(World w, String name, {bool affixed = false}) {
    final e = EquipmentRules.generate(w, name, affixed);
    w.equipment[e.id] = e;
    return e;
  }

  static void award(World w, FactWriter f, String origin) {
    final e = addEquipment(
      w,
      w.equipmentRandom.next(2) == 0 ? '青锋剑' : '玄铁甲',
      affixed: true,
    );
    f.event(
      'equipmentReward',
      '获得${e.name}',
      e.description,
      [w.playerId],
      causes: [Cause(origin, CausalKind.direct)],
    );
  }

  static int affix(World w, String name) => [
    w.equipment[w.weaponId],
    w.equipment[w.armorId],
  ].whereType<Equipment>().fold(0, (sum, e) => sum + (e.effects[name] ?? 0));
  static void start(World w) {
    w.battleQi = EquipmentRules.maxQi(w);
    w.battleRound = 0;
    w.battleHp = w.entities[w.battleTarget]!.hp;
  }

  static int enemyKind(World w) => SeedRandom.hash(w.battleTarget ?? '') % 4;
  static String omen(World w) {
    if (w.battleTarget == null) return '';
    final special = w.battleRound % 2 == 1;
    const hints = [
      '凝气蓄力，下一合将施展猛击',
      '收势护身，下一合将减免伤害',
      '步法连变，下一合将连续出招',
      '丹气汇聚，下一合将恢复气血',
    ];
    return special ? hints[enemyKind(w)] : '对方试探出招；一合之后将显露强招。';
  }

  static int attack(World w, String? skill) {
    if (skill != null && (!w.techniques.contains(skill) || skill != w.style)) {
      throw const RuleViolation('需装备并掌握对应流派');
    }
    final cost = skill == '御剑诀' ? 4 : 3;
    if (skill != null && w.battleQi < cost) throw const RuleViolation('战斗灵力不足');
    if (skill != null) w.battleQi -= cost;
    if (skill == '长春诀') {
      final before = w.player.hp;
      w.player.hp = (w.player.hp + GameCommandService.maxHp(w.player) ~/ 4)
          .clamp(0, GameCommandService.maxHp(w.player));
      w.recordCombat(healing: w.player.hp - before);
      return 0;
    }
    var damage =
        w.player.attributes.scale(
          18 + w.player.realm * 14,
          w.player.attributes.physique,
          2,
        ) +
        EquipmentRules.stats(w).attack;
    damage = damage * (100 + w.player.stage * 5) ~/ 100;
    if (skill == '御剑诀') damage = damage * 18 ~/ 10;
    if (w.battleTarget != null &&
        enemyKind(w) == 1 &&
        w.battleRound % 2 == 1 &&
        skill != '天机诀') {
      damage = (damage + 1) ~/ 2;
    }
    return damage;
  }

  static void counter(
    World w,
    FactWriter f, {
    bool defend = false,
    bool disrupt = false,
  }) {
    final n = w.entities[w.battleTarget]!;
    final special = w.battleRound % 2 == 1 && !disrupt;
    var damage = (12 + n.realm * 12) * (100 + n.stage * 5) ~/ 100;
    final kind = enemyKind(w);
    if (special && kind == 0) damage *= 2;
    if (special && kind == 2) damage = damage * 15 ~/ 10;
    if (special && kind == 3) {
      n.hp = (n.hp + GameCommandService.maxHp(n) ~/ 5).clamp(
        0,
        GameCommandService.maxHp(n),
      );
      damage = 0;
    }
    if (damage > 0) {
      damage = (damage - EquipmentRules.stats(w).defense).clamp(3, 300);
    }
    if (defend) damage = (damage + 1) ~/ 2;
    w.recordCombat(received: damage.clamp(0, w.player.hp));
    w.player.hp -= damage;
    w.battleHp = n.hp;
    w.battleRound++;
    final e = f.event(
      'counterattack',
      '${n.name}${special ? const ['猛击', '守势', '连击', '恢复'][kind] : '反击'}',
      '${w.player.name}受到 $damage 伤害。${disrupt ? '预告招式被破除。' : ''}',
      [n.id, w.playerId],
      causes: [Cause(w.battleOrigin!, CausalKind.direct)],
      witnessed: w.events[w.battleOrigin]?.kind != 'secretKill',
    );
    if (w.player.hp <= 0) f.die(w.player, e);
  }

  static List<Map<String, dynamic>> intelligence(World w, String npc) => w
      .knowledge
      .values
      .where(
        (k) =>
            k.observer == npc &&
            w.events.containsKey(k.subject) &&
            w.events[k.subject]!.participants.every((p) => w.knows(npc, p)),
      )
      .take(12)
      .map(
        (k) => {
          'id': k.subject,
          'title': w.events[k.subject]!.title,
          'text': w.events[k.subject]!.description,
          'confirmed': k.confirmed,
          'source': k.source,
        },
      )
      .toList();

  static void talk(World w, FactWriter f, GameCommand c) {
    final n = w.entities[c.target];
    if (n == null ||
        !n.alive ||
        n.type != KarmaNodeType.npc ||
        n.location != w.player.location ||
        !w.knows(w.playerId, n.id)) {
      throw const RuleViolation('只能与附近已知修士交谈');
    }
    if (c.item == null ||
        c.item!.trim().isEmpty ||
        c.item!.runes.length > 300) {
      throw const RuleViolation('交谈内容为1至300字');
    }
    final reply =
        c.proposal?['reply'] as String? ?? '山河多变，修行须谨慎。若有救助、交易或结交之意，还请以行动相待。';
    w.dialogue.add(DialogueTurn(n.id, c.item!, reply, w.day));
    f.event(
      'dialogue',
      '与${n.name}交谈',
      '${w.player.name}：${c.item}\n${n.name}：$reply\n（人物言论，不代表客观事实）',
      [w.playerId, n.id],
    );
    for (final id in List<String>.from(c.proposal?['news'] ?? [])) {
      final k = w.knowledge['${n.id}|$id'];
      if (k == null) throw const RuleViolation('人物不知此情报');
      f.reveal(
        w.events[id]!,
        w.playerId,
        k.confirmed ? InformationChannel.told : InformationChannel.rumor,
        confirmed: k.confirmed,
        source: n.id,
      );
    }
  }

  static List<Map<String, dynamic>> worldCatalog(World w) {
    final actors = w.entities.values
        .where(
          (n) =>
              n.type == KarmaNodeType.npc &&
              n.alive &&
              w.knows(w.playerId, n.id) &&
              n.id != w.battleTarget &&
              n.lastActed < w.day,
        )
        .take(6);
    final options = <Map<String, dynamic>>[];
    for (final n in actors) {
      void add(String kind, {String? target, String? cause, String? relation}) {
        options.add({
          'id': 'w${options.length}',
          'kind': kind,
          'actor': n.id,
          'name': n.name,
          'target': target,
          'cause': cause,
          'relation': relation,
          'personality': n.personality,
          'realm': n.realm,
        });
      }

      if ([
            PlaceKind.town,
            PlaceKind.market,
          ].contains(w.mapPlaces[n.location]?.kind) &&
          (n.supplies['灵草'] ?? 0) > 0) {
        add('trade');
      }
      final road = w.mapRoads.values
          .where(
            (r) =>
                (r.a == n.location || r.b == n.location) &&
                w.knows(n.id, r.other(n.location)) &&
                n.coins >= r.fee &&
                r.travelDays(n.realm) <= w.day - n.lastActed,
          )
          .firstOrNull;
      if (road != null) add('migration', target: road.other(n.location));
      final other = w.entities.values
          .where(
            (e) =>
                e.type == KarmaNodeType.npc &&
                e.alive &&
                e.id != n.id &&
                e.location == n.location &&
                w.knows(n.id, e.id),
          )
          .firstOrNull;
      if (other != null) {
        add('friendship', target: other.id);
        if (n.coins >= 5) add('investigation', target: other.id);
      }
      for (final r in w.relations.values.where(
        (r) =>
            r.source == n.id &&
            !r.resolved &&
            r.status == RelationStatus.active &&
            w.knows(n.id, r.id) &&
            w.knows(n.id, r.target) &&
            w.entities[r.target]?.alive == true &&
            w.entities[r.target]?.location == n.location,
      )) {
        if (r.type == KarmaRelationType.gratitude &&
            n.realm >= 1 &&
            n.coins >= 35 &&
            w.day - r.created >= 90) {
          final cause = r.events
              .where(
                (id) => w.events[id]?.kind == 'rescue' && w.knows(n.id, id),
              )
              .firstOrNull;
          if (cause != null) {
            add('repayment', target: r.target, cause: cause, relation: r.id);
          }
        }
        if (r.type == KarmaRelationType.hatred &&
            r.target == w.playerId &&
            w.battleTarget == null) {
          final cause = r.events
              .where((id) => w.knows(n.id, id) && w.events[id]?.kind == 'news')
              .firstOrNull;
          if (cause != null) {
            add('revenge', target: r.target, cause: cause, relation: r.id);
          }
        }
      }
    }
    return options;
  }

  static void worldProposal(World w, Map<String, dynamic> proposal) {
    if (w.frozen ||
        w.encounter != null ||
        w.battleTarget != null ||
        w.tribulation != null ||
        w.secretRun != null) {
      return;
    }
    final option = worldCatalog(
      w,
    ).where((o) => o['id'] == proposal['action']).firstOrNull;
    if (option == null) return;
    final n = w.entities[option['actor']]!;
    final f = FactWriter(w);
    final t = option['target'] as String?;
    final kind = option['kind'];
    if (kind == 'migration') {
      final road = w.mapRoads.values.firstWhere(
        (r) =>
            (r.a == n.location && r.b == t) || (r.b == n.location && r.a == t),
      );
      n.coins -= road.fee;
      n.location = t!;
    }
    if (kind == 'trade') {
      n.supplies['灵草'] = n.supplies['灵草']! - 1;
      n.coins += 4;
    }
    if (kind == 'investigation') n.coins -= 5;
    if (kind == 'migration') {
      MapRules.revealNearby(w, n.id, InformationChannel.witness);
    }
    final e = f.event(
      kind == 'trade'
          ? 'npcTrade'
          : kind == 'friendship'
          ? 'npcFriendship'
          : kind,
      '${n.name}：${const {'migration': '迁行', 'trade': '交易', 'friendship': '结交', 'investigation': '调查', 'repayment': '报恩', 'revenge': '复仇'}[kind]}',
      proposal['text'],
      [n.id, ?t],
      location: n.location,
      causes: [
        if (option['cause'] != null) Cause(option['cause'], CausalKind.direct),
      ],
    );
    if (kind == 'friendship') {
      f.relation(
        n.id,
        t!,
        KarmaRelationType.friendship,
        e,
        bidirectional: true,
        strength: 10,
      );
    }
    if (kind == 'investigation') {
      for (final k
          in w.knowledge.values
              .where(
                (k) =>
                    k.observer == t &&
                    k.confirmed &&
                    w.events.containsKey(k.subject),
              )
              .take(2)
              .toList()) {
        f.reveal(
          w.events[k.subject]!,
          n.id,
          InformationChannel.told,
          source: t,
        );
      }
    }
    if (kind == 'repayment') {
      n.coins -= 35;
      w.entities[t]!.coins += 35;
      final r = w.relations[option['relation']]!;
      r.status = RelationStatus.settled;
      r.updated = w.day;
      r.events.add(e.id);
      for (final observer in [n.id, t!]) {
        w.discover(observer, r.id, InformationChannel.witness, source: e.id);
      }
    }
    if (kind == 'revenge') {
      w.battleTarget = n.id;
      w.battleOrigin = e.id;
      w.battleReward = null;
      start(w);
    }
    n.lastActed = w.day;
  }
}
